data:
    !BraTSDataModule {
        data_properties: ~/Decathlon/Task01_BrainTumour/dataset.json,
        spacing: [1.0, 1.0, 1.0],
        spatial_size: [128, 128, 128],
        num_splits: 5,
        split: 1,
        batch_size: 1,
        num_workers: 4,
        cache_num: 4,
        cache_rate: 1.0,
        seed: 42,
    }

task:
    - !SemanticSegmentation
    - network:
          - !SegmentationFactorizer
          - in_channels: 4
            out_channels: 3
            spatial_size: [128, 128, 128]
            encoder_depth: [1, 1, 1, 1, 1]
            encoder_width: [32, 64, 128, 256, 512]
            strides: [1, 2, 2, 2, 2]
            decoder_depth: [1, 1, 1, 1]
            stem: [!Conv3d , { kernel_size: 3, padding: 1, bias: False }]
            downsample: [!Conv3d , { kernel_size: 2, bias: False }]
            upsample: [!ConvTranspose3d , { kernel_size: 2 }]
            head: [!Conv3d , { kernel_size: 1 }]
            pos_embed: True
            num_deep_supr: 3
            dropout: 0.1
            nmf:
                - !FactorizerSubblock
                - ratio: 1
                  tensorize: [!SWMatricize , { head_dim: 8, patch_size: 8 }]
                  act: !ReLU
                  factorize: !NMF
                  rank: 1
                  num_iters: 11
                  num_grad_steps: Null
                  init: uniform
                  solver: hals
                  dropout: 0.1
            mlp:
                - !MLP
                - ratio: 2
                  dropout: 0.1
      inferer:
          !BraTSInferer {
              spacing: [1.0, 1.0, 1.0],
              spatial_size: [128, 128, 128],
              overlap: 0.5,
              post: one-hot-nested,
          }
      loss:
          !DeepSuprLoss {
              loss: !DiceCELoss ,
              include_background: True,
              sigmoid: True,
              squared_pred: True,
          }
      metrics:
          dice:
              !DiceMetric { include_background: True, include_zero_masks: True }
          hd:
              !HausdorffDistanceMetric {
                  include_background: True,
                  include_zero_masks: True,
                  percentile: 95,
              }
      optimizer:
          - !AdamW
          - { lr: 0.0001, weight_decay: 0.01 }
      scheduler:
          - !WarmupCosineSchedule
          - { warmup_steps: 2000, total_steps: 100000 }
      scheduler_config:
          interval: step

training:
    max_steps: 100000
    max_epochs: 9223372036854775807
    gpus: 2
    num_nodes: 1
    accelerator: ddp
    check_val_every_n_epoch: 50
    callbacks:
        - !LearningRateMonitor { logging_interval: step }
        - !ModelCheckpoint { every_n_train_steps: 50 }
        - !SaveValResults {
              save_path: logs/brats/fold1/swin-factorizer/version_0/results_iters11.csv,
          }
    logger:
        !TensorBoardLogger { save_dir: logs/brats/fold1, name: swin-factorizer }

test:
    checkpoint:
        checkpoint_path: logs/brats/fold1/swin-factorizer/version_0/checkpoints/epoch=515-step=99999.ckpt
    inferer:
        !BraTSInferer {
            spacing: [1.0, 1.0, 1.0],
            spatial_size: [128, 128, 128],
            overlap: 0.5,
            post: class,
            write_dir: logs/brats/fold1/swin-factorizer/version_0/predictions,
        }
