data:
    !BraTSDataModule {
        data_properties: /scratch/leuven/336/vsc33647/BraTS2021/dataset.json,
        version: brats2021,
        spacing: [1.0, 1.0, 1.0],
        spatial_size: [128, 128, 128],
        num_splits: 5,
        split: 0,
        batch_size: 1,
        num_workers: 4,
        cache_num: 4,
        cache_rate: 1.0,
        seed: 42,
    }

task:
    - !SemanticSegmentation
    - network:
          - !UNet
          - in_channels: 4
            out_channels: 3
            spatial_dims: 3
            encoder_depth: [1, 1, 1, 1, 1]
            encoder_width: [32, 64, 128, 256, 512]
            strides: [1, 2, 2, 2, 2]
            decoder_depth: [1, 1, 1, 1]
            stem: [!Conv3d , { kernel_size: 3, padding: 1, bias: False }]
            downsample: [!Conv3d , { kernel_size: 2, bias: False }]
            upsample: [!ConvTranspose3d , { kernel_size: 2 }]
            head: [!Conv3d , { kernel_size: 1 }]
            num_deep_supr: 3
            block: !Same
                - - !DoubleConv
                  - conv: [!Conv3d , { kernel_size: 3, padding: 1 }]
                    norm: [!GroupNorm , [8]]
                    act: !LeakyReLU
      inferer:
          !BraTSInferer {
              version: brats2021,
              spacing: [1.0, 1.0, 1.0],
              spatial_size: [128, 128, 128],
              overlap: 0.5,
              post: one-hot-nested,
          }
      loss:
          !DeepSuprLoss {
              loss: !DiceCELoss ,
              include_background: True,
              sigmoid: True,
              squared_pred: True,
          }
      metrics:
          dice:
              !DiceMetric { include_background: True, include_zero_masks: True }
          hd:
              !HausdorffDistanceMetric {
                  include_background: True,
                  include_zero_masks: True,
                  percentile: 95,
              }
      optimizer:
          - !AdamW
          - { lr: 0.0001, weight_decay: 0.01 }
      scheduler:
          - !WarmupCosineSchedule
          - { warmup_steps: 2000, total_steps: 100000 }
      scheduler_config:
          interval: step

training:
    max_steps: 100000
    max_epochs: 9223372036854775807
    gpus: 2
    num_nodes: 1
    accelerator: ddp
    check_val_every_n_epoch: 2
    callbacks:
        - !LearningRateMonitor { logging_interval: step }
        - !ModelCheckpoint { every_n_train_steps: 50 }
        - !SaveValResults {
              save_path: logs/brats2021/fold0/unet/version_0/results.csv,
          }
    logger: !TensorBoardLogger { save_dir: logs/brats2021/fold0, name: unet }

test:
    checkpoint:
        checkpoint_path: logs/brats2021/fold0/unet/version_0/checkpoints/epoch=199-step=99999.ckpt
    inferer:
        !BraTSInferer {
            version: brats2021,
            spacing: [1.0, 1.0, 1.0],
            spatial_size: [128, 128, 128],
            overlap: 0.5,
            post: class,
            write_dir: logs/brats2021/fold0/unet/version_0/predictions,
        }
